# Generated by Django 4.0 on 2022-01-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('alt', models.CharField(default='', max_length=254)),
                ('image', models.ImageField(upload_to='')),
                ('photographer', models.CharField(max_length=254)),
                ('model', models.CharField(max_length=254)),
                ('designer', models.CharField(max_length=254)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
