# Generated by Django 4.0 on 2022-01-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_image_designer_alter_image_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaintingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('alt', models.CharField(default='', max_length=254)),
                ('image', models.ImageField(upload_to='')),
                ('photographer', models.CharField(blank=True, default='', max_length=254, null=True)),
                ('model', models.CharField(blank=True, default='', max_length=254, null=True)),
                ('designer', models.CharField(blank=True, default='', max_length=254, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
